# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: arm64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
#      - name: Install dependencies
#        run: sudo apt install quilt qemu-user-static debootstrap libarchive-tools qemu-utils

      - name: Cleanup last job
        run: sudo rm -rf "/home/ubuntu/actions-runner/_work/pi/pi/deploy"

      - name: Build
        run: sudo ./build-docker.sh
      
      - name: List deploy directory
        run: ls deploy
        
      - name: Upload to Github Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           file: "deploy/*.zip"
           tags: true
         
